# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: retrieve_time.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13retrieve_time.proto\"\x0e\n\x0c\x45mptyMessage\"\'\n\x18PingRetrieveTimeResponse\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\t2L\n\x0cRetrieveTime\x12<\n\x10PingRetrieveTime\x12\r.EmptyMessage\x1a\x19.PingRetrieveTimeResponseb\x06proto3')



_EMPTYMESSAGE = DESCRIPTOR.message_types_by_name['EmptyMessage']
_PINGRETRIEVETIMERESPONSE = DESCRIPTOR.message_types_by_name['PingRetrieveTimeResponse']
EmptyMessage = _reflection.GeneratedProtocolMessageType('EmptyMessage', (_message.Message,), {
  'DESCRIPTOR' : _EMPTYMESSAGE,
  '__module__' : 'retrieve_time_pb2'
  # @@protoc_insertion_point(class_scope:EmptyMessage)
  })
_sym_db.RegisterMessage(EmptyMessage)

PingRetrieveTimeResponse = _reflection.GeneratedProtocolMessageType('PingRetrieveTimeResponse', (_message.Message,), {
  'DESCRIPTOR' : _PINGRETRIEVETIMERESPONSE,
  '__module__' : 'retrieve_time_pb2'
  # @@protoc_insertion_point(class_scope:PingRetrieveTimeResponse)
  })
_sym_db.RegisterMessage(PingRetrieveTimeResponse)

_RETRIEVETIME = DESCRIPTOR.services_by_name['RetrieveTime']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTYMESSAGE._serialized_start=23
  _EMPTYMESSAGE._serialized_end=37
  _PINGRETRIEVETIMERESPONSE._serialized_start=39
  _PINGRETRIEVETIMERESPONSE._serialized_end=78
  _RETRIEVETIME._serialized_start=80
  _RETRIEVETIME._serialized_end=156
# @@protoc_insertion_point(module_scope)
